//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetBuilder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2vEL3BYgOQwLEXbI")]
        public string hVUKBayRaFJRSjL {
            get {
                return ((string)(this["hVUKBayRaFJRSjL"]));
            }
            set {
                this["hVUKBayRaFJRSjL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rVjBNFk75iw0UXA3")]
        public string XmgJQbghcPMmtta {
            get {
                return ((string)(this["XmgJQbghcPMmtta"]));
            }
            set {
                this["XmgJQbghcPMmtta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cwq2c_c")]
        public string apicompanyname {
            get {
                return ((string)(this["apicompanyname"]));
            }
            set {
                this["apicompanyname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("staging.connectwisedev.com")]
        public string apisite {
            get {
                return ((string)(this["apisite"]));
            }
            set {
                this["apisite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TimesheetBuilder")]
        public string apicookie {
            get {
                return ((string)(this["apicookie"]));
            }
            set {
                this["apicookie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:00")]
        public string starttime {
            get {
                return ((string)(this["starttime"]));
            }
            set {
                this["starttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:00")]
        public string endtime {
            get {
                return ((string)(this["endtime"]));
            }
            set {
                this["endtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CW-Admin, Sales")]
        public string adminchargecode {
            get {
                return ((string)(this["adminchargecode"]));
            }
            set {
                this["adminchargecode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mlaplante")]
        public string memberid {
            get {
                return ((string)(this["memberid"]));
            }
            set {
                this["memberid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lunchdeduct {
            get {
                return ((string)(this["lunchdeduct"]));
            }
            set {
                this["lunchdeduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string adminchargecodeid {
            get {
                return ((string)(this["adminchargecodeid"]));
            }
            set {
                this["adminchargecodeid"] = value;
            }
        }
    }
}
